[package]
name = "client"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.5.0", features = [ "net", "io-util" ] }
argh = "0.1"
webpki-roots = "0.22.0"
